#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"Callisto"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/callisto_w.c"
	CHARACTERISTIC_AIM_SKILL					0.1
	CHARACTERISTIC_AIM_ACCURACY					0.25
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					3.25

	CHARACTERISTIC_CHAT_FILE					"bots/callisto_t.c"
	CHARACTERISTIC_CHAT_NAME					"callisto"
	CHARACTERISTIC_CHAT_CPM						95
	CHARACTERISTIC_CHAT_INSULT					0.6
	CHARACTERISTIC_CHAT_MISC					0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					0.65
	CHARACTERISTIC_CHAT_DEATH					0.7
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.65
	CHARACTERISTIC_CHAT_HITTALKING				0.7
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.1
	CHARACTERISTIC_GRAPPLE_USER					0.1

	CHARACTERISTIC_ITEMWEIGHTS					"bots/callisto_i.c"
	CHARACTERISTIC_AGGRESSION					0.55
	CHARACTERISTIC_SELFPRESERVATION				0.6
	CHARACTERISTIC_VENGEFULNESS					0.7
	CHARACTERISTIC_CAMPER						0.1

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.35

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.05
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.05
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.15
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.5
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.3
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.3
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.2

	CHARACTERISTIC_FIRETHROTTLE					0.15
}

skill 4
{
	CHARACTERISTIC_NAME							"Callisto"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/callisto_w.c"
	CHARACTERISTIC_AIM_SKILL					0.3
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					1.5

	CHARACTERISTIC_CHAT_FILE					"bots/callisto_t.c"
	CHARACTERISTIC_CHAT_NAME					"callisto"
	CHARACTERISTIC_CHAT_CPM						95
	CHARACTERISTIC_CHAT_INSULT					0.6
	CHARACTERISTIC_CHAT_MISC					0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					0.65
	CHARACTERISTIC_CHAT_DEATH					0.7
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.65
	CHARACTERISTIC_CHAT_HITTALKING				0.7
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.9
	CHARACTERISTIC_GRAPPLE_USER					0.9

	CHARACTERISTIC_ITEMWEIGHTS					"bots/callisto_i.c"
	CHARACTERISTIC_AGGRESSION					0.55
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.9
	CHARACTERISTIC_CAMPER						0.15

	CHARACTERISTIC_EASY_FRAGGER					0.75
	CHARACTERISTIC_ALERTNESS					0.45

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.25
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.45
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.2
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.15
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.25
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.4
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.3
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.3
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.7
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.5
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.5
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.4

	CHARACTERISTIC_FIRETHROTTLE					0.4
}

skill 5
{
	CHARACTERISTIC_NAME							"Callisto"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/callisto_w.c"
	CHARACTERISTIC_AIM_SKILL					0.65
	CHARACTERISTIC_AIM_ACCURACY					0.75
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/callisto_t.c"
	CHARACTERISTIC_CHAT_NAME					"callisto"
	CHARACTERISTIC_CHAT_CPM						95
	CHARACTERISTIC_CHAT_INSULT					0.6
	CHARACTERISTIC_CHAT_MISC					0.45
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					0.65
	CHARACTERISTIC_CHAT_DEATH					0.7
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.65
	CHARACTERISTIC_CHAT_HITTALKING				0.7
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.75
	CHARACTERISTIC_WEAPONJUMPING				0.9
	CHARACTERISTIC_GRAPPLE_USER					0.9

	CHARACTERISTIC_ITEMWEIGHTS					"bots/callisto_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.65
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.1

	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					0.75

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.45
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.85
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.45
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.25
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.6
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.65
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.4
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.6
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.8
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.7

	CHARACTERISTIC_FIRETHROTTLE					0.85
}
